version: '3'

services:
  web:
    build: ./web
    ports:
      - ${HTTPS_APACHE_PORT}:80
      - "443:443"
    command: sh /init.sh
    volumes:
      - ${HTTPS_SRC}:/var/www/html
      - ./web/sites:/etc/apache2/sites-enabled
      - ./web/supervisor/queue.conf:/etc/supervisor/conf.d/queue.conf
      - ./web/init.sh:/init.sh
      - ./logs/web:/var/log/apache2
      - ./logs/supervisor:/var/log/supervisor

  db_core:
    image: mysql:5.7
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    ports:
      - 4567:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db_core

  redis:
    image: redis

volumes:
  db_core:
